### ISSUE TITLE
Running tests with PHP in a docker container

### ISSUE THREAD

**Issue by pmartin** [atoum/phpstorm-plugin#36]
I have a version of PHP on my local computer and can run tests successfully with it, which means the plugin works, which is great!  
But its not *the right PHP version* (and config and extensions) for my project, and I'd rather run tests using the docker container which contains *the right PHP version* (and configuration and extensions) I'm supposed to use on my project.

Judging from a conversation with @agallou, this means the plugin needs to be updated, so it uses one of the PHP interpreters defines in PhpStorm's configuration, instead of just using the one found in $PATH.

**Comment by Grummfy** [comment]
very good idea!
