### ISSUE TITLE
Tests do not start

### ISSUE THREAD

**Issue by jubianchi** [atoum/phpstorm-plugin#51]
When the plugin can't find the atoum binary, the user has no clue on what's happening. The plugin panel seems ok, saying it's "Starting":

<img width="834" alt="capture d ecran 2016-02-05 a 21 56 18" src="https://cloud.githubusercontent.com/assets/327237/12858982/8e05be88-cc53-11e5-83e8-9701792f46ff.png">

I think we should push a message in the event log or somewhere else... I don't know if it's hard to do or not ;)

**Comment by agallou** [comment]
we could start by adding something like this : 

![capture du 2016-02-07 18 57 49](https://cloud.githubusercontent.com/assets/320372/12874049/c091a072-cdcc-11e5-9c77-d0c1e2bf09cc.png)

**Comment by jubianchi** [comment]
perfect!
