### ISSUE TITLE
Set -mcn option?

### ISSUE THREAD

**Issue by mnapoli** [atoum/phpstorm-plugin#65]
Is there a way to set the `-mcn` option for the plugin? We have some functional tests (that hit the database for example), we need to launch them with `-mcn 1`. I couldn't find a way to set that in the config, maybe it can be used as a workaround?

**Comment by agallou** [comment]
@mnapoli what did you think about that ?
Having a `.atoum.phpstorm.php` file that we load if we found it were different options like `$script->setMaxChildrenNumber(1)` could be defined. 
The file would be shared by the whole team and also versionned.

**Comment by mnapoli** [comment]
I'll give it a try!

**Comment by agallou** [comment]
@mnapoli the feature isn't there yet. If you think that you could work with that kind of feature, I will work on it.

**Comment by mnapoli** [comment]
Ah OK :) Then yes that might be a good solution!
